package nl.bandit.warps.command;
import nl.bandit.warps.*; import nl.bandit.warps.model.Warp; import org.bukkit.command.*; import org.bukkit.entity.Player; import java.util.*;
public final class WarpCommand implements CommandExecutor,TabCompleter {
 private final BanditWarpsPlugin plugin; public WarpCommand(BanditWarpsPlugin plugin){this.plugin=plugin;}
 private void msg(CommandSender s,String m){s.sendMessage(plugin.getConfig().getString("prefix","&6BanditWarps &8» ").replace('&','§')+m.replace('&','§'));}
 public boolean onCommand(CommandSender s,Command c,String label,String[] a){if(!(s instanceof Player p)){msg(s,"&cAlleen spelers.");return true;}if(a.length==0){plugin.menus().browser(p);return true;}String sub=a[0].toLowerCase(Locale.ROOT);
  if(sub.equals("create")){if(!p.hasPermission("banditwarps.create")){msg(p,"&cGeen permissie.");return true;}if(a.length<2){msg(p,"&7/pwarp create <naam>");return true;}String n=a[1];if(!n.matches("[A-Za-z0-9_-]{3,20}")||plugin.warps().get(n)!=null){msg(p,"&cOngeldige of bestaande naam.");return true;}long own=plugin.warps().all().stream().filter(w->w.owner.equals(p.getUniqueId())).count();if(own>=plugin.getConfig().getInt("max-warps-per-player",5)){msg(p,"&cJe hebt je warp-limiet bereikt.");return true;}Warp w=new Warp(n.toLowerCase(Locale.ROOT),p.getUniqueId(),n,p.getLocation());plugin.warps().put(w);plugin.menus().settings(p,w);return true;}
  if(sub.equals("go")){Warp w=a.length>1?plugin.warps().get(a[1]):null;if(w==null||(!w.isPublic&&!w.owner.equals(p.getUniqueId())&&!p.hasPermission("banditwarps.admin"))){msg(p,"&cWarp niet gevonden of privé.");return true;}p.teleportAsync(w.location);if(!w.owner.equals(p.getUniqueId())){long now=System.currentTimeMillis(),cd=plugin.getConfig().getLong("visitor-cooldown-minutes",15)*60000L;if(now-w.cooldowns.getOrDefault(p.getUniqueId(),0L)>=cd){w.cooldowns.put(p.getUniqueId(),now);w.visitors++;plugin.warps().put(w);}}msg(p,"&aGeteleporteerd naar &f"+w.name);return true;}
  if(List.of("edit","delete","description").contains(sub)){Warp w=a.length>1?plugin.warps().get(a[1]):null;if(w==null||(!w.owner.equals(p.getUniqueId())&&!p.hasPermission("banditwarps.admin"))){msg(p,"&cWarp niet gevonden of geen permissie.");return true;}if(sub.equals("edit"))plugin.menus().settings(p,w);else if(sub.equals("delete")){plugin.warps().remove(w);msg(p,"&aWarp verwijderd.");}else {if(a.length<3){msg(p,"&7/pwarp description <warp> <tekst>");return true;}w.description=String.join(" ",Arrays.copyOfRange(a,2,a.length));plugin.warps().put(w);msg(p,"&aBeschrijving aangepast.");}return true;}
  if(sub.equals("list")){plugin.menus().owned(p);return true;}if(sub.equals("admin")&&p.hasPermission("banditwarps.admin")&&a.length>1&&a[1].equalsIgnoreCase("reload")){plugin.reloadAll();msg(p,"&aConfiguratie herladen.");return true;}msg(p,"&7/pwarp <create|go|edit|description|delete|list>");return true;
 }
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[]a){if(a.length==1)return List.of("create","go","edit","description","delete","list","admin").stream().filter(x->x.startsWith(a[0].toLowerCase())).toList();if(a.length==2&&List.of("go","edit","description","delete").contains(a[0]))return plugin.warps().all().stream().map(w->w.name).filter(n->n.toLowerCase().startsWith(a[1].toLowerCase())).toList();return List.of();}
}
