package nl.bandit.warps.command;
import nl.bandit.warps.BanditWarpsPlugin; import nl.bandit.warps.model.Warp;
import org.bukkit.command.*; import org.bukkit.entity.Player;
import java.util.*;

public final class WarpCommand implements CommandExecutor,TabCompleter {
 private final BanditWarpsPlugin plugin; public WarpCommand(BanditWarpsPlugin plugin){this.plugin=plugin;}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!(sender instanceof Player player)){plugin.message(sender,"players-only",Map.of());return true;}if(!player.hasPermission("banditwarps.use")){plugin.message(player,"no-permission",Map.of());return true;}if(args.length==0){plugin.menus().browser(player);return true;}String sub=args[0].toLowerCase(Locale.ROOT);
  if(sub.equals(plugin.word("create"))){create(player,args);return true;}if(sub.equals(plugin.word("go"))){go(player,args);return true;}if(sub.equals(plugin.word("edit"))){edit(player,args);return true;}if(sub.equals(plugin.word("delete"))){delete(player,args);return true;}if(sub.equals(plugin.word("list"))){plugin.menus().owned(player);return true;}if(sub.equals(plugin.word("admin"))){admin(player,args);return true;}plugin.message(player,"unknown-command",Map.of());return true;}
 private void create(Player player,String[] args){if(!player.hasPermission("banditwarps.create")){plugin.message(player,"no-permission",Map.of());return;}if(args.length<2){plugin.message(player,"usage-create",Map.of("%command%",plugin.word("create")));return;}String name=args[1];if(!validName(name)){plugin.message(player,"invalid-name",Map.of("%min%",String.valueOf(plugin.getConfig().getInt("validation.name-min-length",3)),"%max%",String.valueOf(plugin.getConfig().getInt("validation.name-max-length",20))));return;}if(!plugin.warps().nameAvailable(name,"")){plugin.message(player,"name-taken",Map.of("%name%",name));return;}int limit=plugin.getConfig().getInt("limits.default",5);for(int value:plugin.getConfig().getIntegerList("limits.permission-tiers"))if(player.hasPermission("banditwarps.limit."+value))limit=Math.max(limit,value);if(plugin.warps().countOwnedBy(player.getUniqueId())>=limit&&!player.hasPermission("banditwarps.admin")){plugin.message(player,"limit-reached",Map.of("%limit%",String.valueOf(limit)));return;}Warp warp=new Warp(UUID.randomUUID().toString(),player.getUniqueId(),name,player.getLocation());plugin.menus().beginEdit(player,warp,true);}
 private void go(Player player,String[] args){if(args.length<2){plugin.message(player,"usage-go",Map.of("%command%",plugin.word("go")));return;}Optional<Warp> found=plugin.warps().findByName(args[1]);if(found.isEmpty()){plugin.message(player,"not-found",Map.of("%warp%",args[1]));return;}Warp warp=found.get();if(!warp.isPublic()&&!warp.owner().equals(player.getUniqueId())&&!player.hasPermission("banditwarps.admin")){plugin.message(player,"private-warp",Map.of("%warp%",warp.name()));return;}plugin.message(player,"teleporting",Map.of("%warp%",warp.name()));player.teleportAsync(warp.location()).thenAccept(success->plugin.getServer().getScheduler().runTask(plugin,()->{if(!success){plugin.message(player,"teleport-failed",Map.of("%warp%",warp.name()));return;}long cooldown=plugin.getConfig().getLong("visitor-cooldown-minutes",15)*60_000L;if(warp.registerVisit(player.getUniqueId(),System.currentTimeMillis(),cooldown))plugin.warps().save(warp);plugin.message(player,"teleported",Map.of("%warp%",warp.name()));}));}
 private void edit(Player player,String[] args){Warp warp=ownedWarp(player,args,plugin.word("edit"));if(warp!=null)plugin.menus().beginEdit(player,warp,false);}
 private void delete(Player player,String[] args){Warp warp=ownedWarp(player,args,plugin.word("delete"));if(warp!=null){plugin.menus().beginEdit(player,warp,false);plugin.menus().openDeleteConfirm(player);}}
 private Warp ownedWarp(Player player,String[] args,String word){if(args.length<2){plugin.message(player,"usage-warp",Map.of("%command%",word));return null;}Optional<Warp> found=plugin.warps().findByName(args[1]);if(found.isEmpty()){plugin.message(player,"not-found",Map.of("%warp%",args[1]));return null;}Warp warp=found.get();if(!warp.owner().equals(player.getUniqueId())&&!player.hasPermission("banditwarps.admin")){plugin.message(player,"not-owner",Map.of());return null;}return warp;}
 private void admin(Player player,String[] args){if(!player.hasPermission("banditwarps.admin")){plugin.message(player,"no-permission",Map.of());return;}if(args.length>1&&args[1].equalsIgnoreCase(plugin.word("reload"))){plugin.reloadAll();plugin.message(player,"reloaded",Map.of());return;}plugin.message(player,"usage-admin",Map.of("%admin%",plugin.word("admin"),"%reload%",plugin.word("reload")));}
 private boolean validName(String name){int min=plugin.getConfig().getInt("validation.name-min-length",3),max=plugin.getConfig().getInt("validation.name-max-length",20);return name.length()>=min&&name.length()<=max&&name.matches(plugin.getConfig().getString("validation.name-regex","[A-Za-z0-9_-]+"));}
 @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return List.of("create","go","edit","delete","list","admin").stream().map(plugin::word).filter(word->word.startsWith(args[0].toLowerCase())).toList();if(args.length==2&&sender instanceof Player player&&List.of(plugin.word("go"),plugin.word("edit"),plugin.word("delete")).contains(args[0].toLowerCase()))return plugin.warps().all().stream().filter(w->args[0].equalsIgnoreCase(plugin.word("go"))||w.owner().equals(player.getUniqueId())||sender.hasPermission("banditwarps.admin")).map(Warp::name).filter(name->name.toLowerCase().startsWith(args[1].toLowerCase())).sorted().toList();if(args.length==2&&args[0].equalsIgnoreCase(plugin.word("admin"))&&sender.hasPermission("banditwarps.admin"))return List.of(plugin.word("reload"));return List.of();}
}
