name: BanditWarps
version: '${project.version}'
main: nl.bandit.warps.BanditWarpsPlugin
api-version: '1.21'
author: Bandit
description: Premium, volledig configureerbare player warps voor Paper.
commands:
  pwarp:
    description: Open of beheer player warps
    aliases:
      - pwarps
      - playerwarp
      - playerwarps
    usage: /pwarp
permissions:
  banditwarps.use:
    default: true
  banditwarps.create:
    default: true
  banditwarps.admin:
    default: op
  banditwarps.icon.default:
    default: true
  banditwarps.icon.home:
    default: true
  banditwarps.icon.shop:
    default: true
