package nl.bandit.warps.menu;
import nl.bandit.warps.BanditWarpsPlugin; import nl.bandit.warps.model.Warp; import org.bukkit.*; import org.bukkit.configuration.ConfigurationSection; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.entity.Player; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import java.io.File; import java.text.SimpleDateFormat; import java.util.*;
public final class MenuService {
 private final BanditWarpsPlugin plugin; private YamlConfiguration menus,icons; private final Map<UUID,Warp> editing=new HashMap<>(); private final Map<UUID,Integer> sort=new HashMap<>();
 public MenuService(BanditWarpsPlugin plugin){this.plugin=plugin;reload();} public void reload(){menus=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"menus.yml"));icons=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"icons.yml"));}
 private String text(String value,Warp w){String owner=Optional.ofNullable(Bukkit.getOfflinePlayer(w.owner).getName()).orElse("Onbekend");String date=new SimpleDateFormat("dd-MM-yyyy HH:mm").format(new Date(w.created));return value.replace("%warp_name%",w.name).replace("%warp_description%",w.description.isBlank()?"&7Geen beschrijving ingesteld.":w.description).replace("%warp_visitors%",""+w.visitors).replace("%warp_icon%",w.icon).replace("%warp_status%",w.isPublic?"&aOpenbaar":"&cPrivé").replace("%warp_owner%",owner).replace("%warp_created%",date).replace('&','§');}
 private ItemStack item(ConfigurationSection s,Warp w){Material m=Material.matchMaterial(s.getString("material","BARRIER"));ItemStack i=new ItemStack(m==null?Material.BARRIER:m);ItemMeta meta=i.getItemMeta();meta.setDisplayName(text(s.getString("name"," "),w));meta.setLore(s.getStringList("lore").stream().map(x->text(x,w)).toList());i.setItemMeta(meta);return i;}
 private Inventory base(String key){int size=menus.getInt(key+".rows",6)*9;Inventory i=Bukkit.createInventory(null,size,menus.getString(key+".title","&0BanditWarps").replace('&','§'));if(menus.getBoolean(key+".border.enabled",true)){Warp blank=new Warp("blank",new UUID(0,0)," ",null);ItemStack border=item(menus.getConfigurationSection(key+".border.item"),blank);for(int s=0;s<size;s++)if(s<9||s>=size-9||s%9==0||s%9==8)i.setItem(s,border);}return i;}
 private ItemStack warpItem(String menu,Warp w){ItemStack i=item(menus.getConfigurationSection(menu+".warp-item"),w);Material m=Material.matchMaterial(icons.getString("icons."+w.icon+".material","ENDER_PEARL"));i.setType(m==null?Material.ENDER_PEARL:m);return i;}
 public void settings(Player p,Warp w){editing.put(p.getUniqueId(),w);Inventory i=base("settings");for(String key:List.of("name","status","description","icon","confirm","cancel")){ConfigurationSection s=menus.getConfigurationSection("settings.items."+key);i.setItem(s.getInt("slot"),item(s,w));}p.openInventory(i);}
 public void icons(Player p,Warp w){Inventory i=base("icons");int slot=menus.getInt("icons.start-slot",10);for(String id:icons.getConfigurationSection("icons").getKeys(false)){if(!p.hasPermission("banditwarps.icon."+id))continue;Warp display=new Warp("icon",p.getUniqueId(),id,p.getLocation());ItemStack icon=item(menus.getConfigurationSection("icons.select-item"),display);Material m=Material.matchMaterial(icons.getString("icons."+id+".material","BARRIER"));icon.setType(m==null?Material.BARRIER:m);i.setItem(slot++,icon);}ConfigurationSection back=menus.getConfigurationSection("icons.back");i.setItem(back.getInt("slot"),item(back,w));p.openInventory(i);}
 public void browser(Player p){Inventory i=base("browser");List<Warp> list=new ArrayList<>(plugin.warps().all());list.removeIf(w->!w.isPublic&&!w.owner.equals(p.getUniqueId()));int mode=sort.getOrDefault(p.getUniqueId(),0);if(mode==0)list.sort(Comparator.comparingInt((Warp w)->w.visitors).reversed());else if(mode==1)list.sort(Comparator.comparingLong(w->w.created).reversed());else if(mode==2)list.sort(Comparator.comparingLong(w->w.created));else Collections.shuffle(list);int slot=menus.getInt("browser.warp-start-slot",10);for(Warp w:list){while(slot<45&&(slot%9==0||slot%9==8))slot++;if(slot>=45)break;i.setItem(slot++,warpItem("browser",w));}Warp blank=new Warp("blank",p.getUniqueId()," ",p.getLocation());ConfigurationSection s=menus.getConfigurationSection("browser.items.sort");ItemStack sortItem=item(s,blank);ItemMeta meta=sortItem.getItemMeta();meta.setLore(List.of("§8━━━━━━━━━━━━━━━━━━━━","§7Huidig: §f"+List.of("Meeste bezoekers","Nieuwste","Oudste","Random")[mode],"","§eKlik om te wisselen"));sortItem.setItemMeta(meta);i.setItem(s.getInt("slot"),sortItem);ConfigurationSection mine=menus.getConfigurationSection("browser.items.your-warps");i.setItem(mine.getInt("slot"),item(mine,blank));p.openInventory(i);}
 public void owned(Player p){Inventory i=base("owned");int slot=menus.getInt("owned.warp-start-slot",10);for(Warp w:plugin.warps().all())if(w.owner.equals(p.getUniqueId())&&slot<45)i.setItem(slot++,warpItem("owned",w));p.openInventory(i);}
 public Warp editing(Player p){return editing.get(p.getUniqueId());} public void nextSort(Player p){sort.put(p.getUniqueId(),(sort.getOrDefault(p.getUniqueId(),0)+1)%4);} public String icon(ItemStack i){for(String id:icons.getConfigurationSection("icons").getKeys(false))if(icons.getString("icons."+id+".material").equals(i.getType().name()))return id;return null;}
 public String title(String key){return menus.getString(key).replace('&','§');} public ItemStack inputItem(String key,Warp w){return item(menus.getConfigurationSection("text-input."+key),w);}
}
