package nl.bandit.warps.menu;
import nl.bandit.warps.BanditWarpsPlugin; import nl.bandit.warps.model.Warp; import org.bukkit.ChatColor; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.inventory.InventoryClickEvent;
public final class MenuListener implements Listener {
 private final BanditWarpsPlugin plugin; public MenuListener(BanditWarpsPlugin plugin){this.plugin=plugin;}
 @EventHandler public void click(InventoryClickEvent event){if(!(event.getWhoClicked() instanceof Player player)||event.getCurrentItem()==null)return;String title=ChatColor.stripColor(event.getView().getTitle());if(!title.equals(ChatColor.stripColor(plugin.menus().title("browser.title")))&&!title.equals(ChatColor.stripColor(plugin.menus().title("owned.title")))&&!title.equals(ChatColor.stripColor(plugin.menus().title("settings.title")))&&!title.equals(ChatColor.stripColor(plugin.menus().title("icons.title"))))return;event.setCancelled(true);if(event.getRawSlot()>=event.getView().getTopInventory().getSize())return;String name=ChatColor.stripColor(event.getCurrentItem().getItemMeta().getDisplayName());Warp warp=plugin.menus().editing(player);
  if(title.equals(ChatColor.stripColor(plugin.menus().title("settings.title")))&&warp!=null){if(name.contains("Naam wijzigen"))plugin.input().open(player,warp,true);else if(name.contains("Status")){warp.isPublic=!warp.isPublic;plugin.warps().put(warp);plugin.menus().settings(player,warp);}else if(name.contains("Beschrijving"))plugin.input().open(player,warp,false);else if(name.contains("icoon"))plugin.menus().icons(player,warp);else if(name.contains("Opslaan")){plugin.warps().put(warp);player.closeInventory();}else if(name.contains("Annuleren"))player.closeInventory();return;}
  if(title.equals(ChatColor.stripColor(plugin.menus().title("icons.title")))&&warp!=null){if(name.contains("Terug")){plugin.menus().settings(player,warp);return;}String icon=plugin.menus().icon(event.getCurrentItem());if(icon!=null){warp.icon=icon;plugin.warps().put(warp);plugin.menus().settings(player,warp);}return;}
  if(title.equals(ChatColor.stripColor(plugin.menus().title("browser.title")))){if(name.contains("Sorteren")){plugin.menus().nextSort(player);plugin.menus().browser(player);return;}if(name.contains("Jouw warps")){plugin.menus().owned(player);return;}}
  for(Warp w:plugin.warps().all())if(ChatColor.stripColor(w.name).equals(name)){if(title.equals(ChatColor.stripColor(plugin.menus().title("owned.title")))&&w.owner.equals(player.getUniqueId()))plugin.menus().settings(player,w);else player.performCommand("pwarp go "+w.name);return;}
 }
}
