package nl.bandit.warps.menu;

import nl.bandit.warps.BanditWarpsPlugin;
import nl.bandit.warps.model.Warp;
import org.bukkit.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;

public final class MenuService {
    private static final List<String> SORT_NAMES=List.of("Meeste bezoekers","Nieuwste","Oudste","Willekeurig");
    private final BanditWarpsPlugin plugin;
    private final NamespacedKey actionKey,warpKey,iconKey;
    private final Map<UUID,EditSession> edits=new HashMap<>();
    private final Map<UUID,Integer> pages=new HashMap<>(),sortModes=new HashMap<>();
    private YamlConfiguration menus,icons;

    public MenuService(BanditWarpsPlugin plugin){this.plugin=plugin;actionKey=new NamespacedKey(plugin,"action");warpKey=new NamespacedKey(plugin,"warp-id");iconKey=new NamespacedKey(plugin,"icon-id");reload();}
    public void reload(){menus=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"menus.yml"));icons=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"icons.yml"));}
    public void beginEdit(Player player,Warp original,boolean newWarp){edits.put(player.getUniqueId(),new EditSession(original,original.copy(),newWarp));openSettings(player);}
    public EditSession edit(Player player){return edits.get(player.getUniqueId());}
    public void cancelEdit(Player player){edits.remove(player.getUniqueId());player.closeInventory();plugin.message(player,"editor-cancelled",Map.of());}
    public boolean saveEdit(Player player){EditSession session=edit(player);if(session==null)return false;Warp draft=session.draft();if(!plugin.warps().nameAvailable(draft.name(),draft.id())){plugin.message(player,"name-taken",Map.of("%name%",draft.name()));return false;}if(session.newWarp())plugin.warps().save(draft);else{session.original().applyEditableFields(draft);plugin.warps().save(session.original());}edits.remove(player.getUniqueId());player.closeInventory();plugin.message(player,session.newWarp()?"created":"saved",Map.of("%warp%",draft.name()));return true;}
    public String action(ItemStack item){return stringTag(item,actionKey);} public String warpId(ItemStack item){return stringTag(item,warpKey);} public String iconId(ItemStack item){return stringTag(item,iconKey);}
    private String stringTag(ItemStack item,NamespacedKey key){if(item==null||!item.hasItemMeta())return null;return item.getItemMeta().getPersistentDataContainer().get(key,PersistentDataType.STRING);}
    private ItemStack tag(ItemStack item,String action){ItemMeta meta=item.getItemMeta();meta.getPersistentDataContainer().set(actionKey,PersistentDataType.STRING,action);item.setItemMeta(meta);return item;}

    private String format(String value,Warp warp,Map<String,String> extra){Location loc=warp.location();String owner=Optional.ofNullable(Bukkit.getOfflinePlayer(warp.owner()).getName()).orElse("Onbekend");String date=new SimpleDateFormat(plugin.getConfig().getString("date-format","dd-MM-yyyy HH:mm")).format(new Date(warp.createdAt()));Map<String,String> values=new HashMap<>(extra);values.put("%warp_name%",warp.name());values.put("%warp_description%",warp.description().isBlank()?plugin.getConfig().getString("empty-description","Geen beschrijving ingesteld."):warp.description());values.put("%warp_owner%",owner);values.put("%warp_visitors%",String.valueOf(warp.visitors()));values.put("%warp_status%",warp.isPublic()?"&aOpenbaar":"&cPrivé");values.put("%warp_icon%",warp.icon());values.put("%warp_created%",date);values.put("%warp_world%",loc.getWorld()==null?"Onbekend":loc.getWorld().getName());values.put("%warp_x%",String.valueOf(loc.getBlockX()));values.put("%warp_y%",String.valueOf(loc.getBlockY()));values.put("%warp_z%",String.valueOf(loc.getBlockZ()));for(Map.Entry<String,String> entry:values.entrySet())value=value.replace(entry.getKey(),entry.getValue());return color(value);}
    private String color(String value){return ChatColor.translateAlternateColorCodes('&',value==null?"":value);}
    private ItemStack item(ConfigurationSection section,Warp warp,Map<String,String> extra){if(section==null)return new ItemStack(Material.BARRIER);Material material=Material.matchMaterial(section.getString("material","BARRIER"));ItemStack item=new ItemStack(material==null?Material.BARRIER:material,Math.max(1,section.getInt("amount",1)));ItemMeta meta=item.getItemMeta();meta.setDisplayName(format(section.getString("name"," "),warp,extra));meta.setLore(section.getStringList("lore").stream().map(line->format(line,warp,extra)).toList());if(section.getBoolean("glow",false))meta.setEnchantmentGlintOverride(true);item.setItemMeta(meta);return item;}
    private Inventory base(String key,MenuType type,Warp context){int size=Math.max(1,Math.min(6,menus.getInt(key+".rows",6)))*9;Inventory inventory=Bukkit.createInventory(new MenuHolder(type),size,color(menus.getString(key+".title","&0BanditWarps")));if(menus.getBoolean(key+".border.enabled",true)){ItemStack border=item(menus.getConfigurationSection(key+".border.item"),context,Map.of());for(int slot=0;slot<size;slot++)if(slot<9||slot>=size-9||slot%9==0||slot%9==8)inventory.setItem(slot,border);}return inventory;}
    private void configuredAction(Inventory inventory,String menu,String key,Warp warp,Map<String,String> vars){ConfigurationSection section=menus.getConfigurationSection(menu+".items."+key);if(section!=null)inventory.setItem(section.getInt("slot"),tag(item(section,warp,vars),key));}
    private void applyIcon(ItemStack item,String id){ConfigurationSection section=icons.getConfigurationSection("icons."+id);if(section==null)section=icons.getConfigurationSection("icons.default");Material material=Material.matchMaterial(section==null?"ENDER_PEARL":section.getString("material","ENDER_PEARL"));item.setType(material==null?Material.ENDER_PEARL:material);if(section!=null&&section.contains("custom-model-data")){ItemMeta meta=item.getItemMeta();meta.setCustomModelData(section.getInt("custom-model-data"));item.setItemMeta(meta);}}
    private ItemStack warpItem(String menu,Warp warp){ItemStack result=item(menus.getConfigurationSection(menu+".warp-item"),warp,Map.of());applyIcon(result,warp.icon());ItemMeta meta=result.getItemMeta();meta.getPersistentDataContainer().set(actionKey,PersistentDataType.STRING,"warp");meta.getPersistentDataContainer().set(warpKey,PersistentDataType.STRING,warp.id());result.setItemMeta(meta);return result;}

    public void browser(Player player){openWarpList(player,"browser",MenuType.BROWSER,plugin.warps().all().stream().filter(w->w.isPublic()||w.owner().equals(player.getUniqueId())||player.hasPermission("banditwarps.admin")).toList());}
    public void owned(Player player){openWarpList(player,"owned",MenuType.OWNED,plugin.warps().all().stream().filter(w->w.owner().equals(player.getUniqueId())).toList());}
    private void openWarpList(Player player,String menu,MenuType type,List<Warp> source){List<Warp> warps=new ArrayList<>(source);int sort=sortModes.getOrDefault(player.getUniqueId(),0);switch(sort){case 0->warps.sort(Comparator.comparingInt(Warp::visitors).reversed());case 1->warps.sort(Comparator.comparingLong(Warp::createdAt).reversed());case 2->warps.sort(Comparator.comparingLong(Warp::createdAt));default->Collections.shuffle(warps);}int perPage=Math.max(1,menus.getIntegerList(menu+".content-slots").size());List<Integer> slots=menus.getIntegerList(menu+".content-slots");if(slots.isEmpty()){slots=new ArrayList<>();for(int s=10;s<45;s++)if(s%9!=0&&s%9!=8)slots.add(s);perPage=slots.size();}int maxPage=Math.max(0,(warps.size()-1)/perPage);int page=Math.max(0,Math.min(pages.getOrDefault(player.getUniqueId(),0),maxPage));pages.put(player.getUniqueId(),page);Warp context=warps.isEmpty()?new Warp("context",player.getUniqueId(),"-",player.getLocation()):warps.get(0);Inventory inventory=base(menu,type,context);int start=page*perPage;for(int i=0;i<perPage&&start+i<warps.size();i++)inventory.setItem(slots.get(i),warpItem(menu,warps.get(start+i)));Map<String,String> vars=Map.of("%page%",String.valueOf(page+1),"%pages%",String.valueOf(maxPage+1),"%sort%",SORT_NAMES.get(sort));configuredAction(inventory,menu,"previous",context,vars);configuredAction(inventory,menu,"next",context,vars);configuredAction(inventory,menu,"sort",context,vars);configuredAction(inventory,menu,"your-warps",context,vars);configuredAction(inventory,menu,"back",context,vars);player.openInventory(inventory);}
    public void nextPage(Player player,boolean forward,MenuType type){pages.merge(player.getUniqueId(),forward?1:-1,Integer::sum);if(type==MenuType.OWNED)owned(player);else browser(player);} public void nextSort(Player player){sortModes.put(player.getUniqueId(),(sortModes.getOrDefault(player.getUniqueId(),0)+1)%SORT_NAMES.size());pages.put(player.getUniqueId(),0);browser(player);}
    public void openSettings(Player player){EditSession session=edit(player);if(session==null)return;Warp draft=session.draft();Inventory inventory=base("settings",MenuType.SETTINGS,draft);for(String key:List.of("name","status","description","icon","save","cancel"))configuredAction(inventory,"settings",key,draft,Map.of());if(!session.newWarp())configuredAction(inventory,"settings","delete",draft,Map.of());player.openInventory(inventory);}
    public void openIcons(Player player){EditSession session=edit(player);if(session==null)return;Warp draft=session.draft();Inventory inventory=base("icons",MenuType.ICONS,draft);List<Integer> slots=menus.getIntegerList("icons.content-slots");int index=0;ConfigurationSection root=icons.getConfigurationSection("icons");if(root!=null)for(String id:root.getKeys(false)){if(index>=slots.size())break;if(!player.hasPermission("banditwarps.icon."+id)&&!player.hasPermission("banditwarps.admin"))continue;String display=root.getString(id+".display-name",id);ItemStack icon=item(menus.getConfigurationSection("icons.icon-item"),draft,Map.of("%icon%",id,"%icon_display%",display,"%selected%",id.equals(draft.icon())?"&aGeselecteerd":"&7Beschikbaar"));applyIcon(icon,id);ItemMeta meta=icon.getItemMeta();meta.getPersistentDataContainer().set(actionKey,PersistentDataType.STRING,"select-icon");meta.getPersistentDataContainer().set(iconKey,PersistentDataType.STRING,id);icon.setItemMeta(meta);inventory.setItem(slots.get(index++),icon);}configuredAction(inventory,"icons","back",draft,Map.of());player.openInventory(inventory);}
    public void openDeleteConfirm(Player player){EditSession session=edit(player);if(session==null||session.newWarp())return;Warp draft=session.draft();Inventory inventory=base("delete-confirm",MenuType.DELETE_CONFIRM,draft);configuredAction(inventory,"delete-confirm","confirm-delete",draft,Map.of());configuredAction(inventory,"delete-confirm","cancel-delete",draft,Map.of());player.openInventory(inventory);}
    public void deleteEdited(Player player){EditSession session=edit(player);if(session==null||session.newWarp())return;plugin.warps().delete(session.original());edits.remove(player.getUniqueId());player.closeInventory();plugin.message(player,"deleted",Map.of("%warp%",session.draft().name()));}
    public String dialogText(String path,String fallback){return menus.getString(path,fallback);}
    public int dialogInt(String path,int fallback){return menus.getInt(path,fallback);}
    public List<String> dialogLines(String path){return menus.getStringList(path);}
}
