package nl.bandit.warps.menu;
import nl.bandit.warps.BanditWarpsPlugin;
import nl.bandit.warps.model.Warp;
import org.bukkit.*; import org.bukkit.configuration.ConfigurationSection; import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.Player; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta;
import java.io.File; import java.util.*;
public final class MenuService {
 private final BanditWarpsPlugin plugin; private YamlConfiguration menus,icons;
 private final Map<UUID,Warp> editing=new HashMap<>(); private final Map<UUID,Integer> sort=new HashMap<>();
 public MenuService(BanditWarpsPlugin plugin){this.plugin=plugin;reload();}
 public void reload(){menus=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"menus.yml"));icons=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"icons.yml"));}
 private String text(String value,Warp warp){return value.replace("%warp_name%",warp.name).replace("%warp_description%",warp.description.isBlank()?"Geen beschrijving":warp.description).replace("%warp_visitors%",""+warp.visitors).replace("%warp_icon%",warp.icon).replace("%warp_status%",warp.isPublic?"&aOpenbaar":"&cPrivé").replace('&','§');}
 private ItemStack configured(ConfigurationSection section,Warp warp){Material material=Material.matchMaterial(section.getString("material","BARRIER"));ItemStack item=new ItemStack(material==null?Material.BARRIER:material);ItemMeta meta=item.getItemMeta();meta.setDisplayName(text(section.getString("name"," "),warp));meta.setLore(section.getStringList("lore").stream().map(line->text(line,warp)).toList());item.setItemMeta(meta);return item;}
 private Inventory inventory(String key){int size=menus.getInt(key+".rows",6)*9;Inventory inventory=Bukkit.createInventory(null,size,menus.getString(key+".title","&8BanditWarps").replace('&','§'));if(menus.getBoolean(key+".border.enabled",true)){Warp blank=new Warp("blank",new UUID(0,0)," ",null);ItemStack border=configured(menus.getConfigurationSection(key+".border.item"),blank);for(int slot=0;slot<size;slot++)if(slot<9||slot>=size-9||slot%9==0||slot%9==8)inventory.setItem(slot,border);}return inventory;}
 private ItemStack warpItem(String menu,Warp warp){ItemStack item=configured(menus.getConfigurationSection(menu+".warp-item"),warp);Material material=Material.matchMaterial(icons.getString("icons."+warp.icon+".material","ENDER_PEARL"));item.setType(material==null?Material.ENDER_PEARL:material);return item;}
 public void settings(Player player,Warp warp){editing.put(player.getUniqueId(),warp);Inventory inv=inventory("settings");for(String key:List.of("status","description","icon","confirm")){ConfigurationSection section=menus.getConfigurationSection("settings.items."+key);inv.setItem(section.getInt("slot"),configured(section,warp));}player.openInventory(inv);}
 public void icons(Player player,Warp warp){Inventory inv=inventory("icons");int slot=menus.getInt("icons.start-slot",10);for(String id:icons.getConfigurationSection("icons").getKeys(false)){if(player.hasPermission("banditwarps.icon."+id)){Material material=Material.matchMaterial(icons.getString("icons."+id+".material"));ItemStack item=new ItemStack(material==null?Material.BARRIER:material);ItemMeta meta=item.getItemMeta();meta.setDisplayName(("&e"+id).replace('&','§'));item.setItemMeta(meta);inv.setItem(slot++,item);}}player.openInventory(inv);}
 public void browser(Player player){Inventory inv=inventory("browser");List<Warp> warps=plugin.warps().all().stream().filter(w->w.isPublic||w.owner.equals(player.getUniqueId())).toList();int slot=menus.getInt("browser.warp-start-slot",10);for(Warp warp:warps)if(slot<45)inv.setItem(slot++,warpItem("browser",warp));Warp blank=new Warp("blank",player.getUniqueId()," ",player.getLocation());ConfigurationSection sortItem=menus.getConfigurationSection("browser.items.sort");inv.setItem(sortItem.getInt("slot"),configured(sortItem,blank));ConfigurationSection mine=menus.getConfigurationSection("browser.items.your-warps");inv.setItem(mine.getInt("slot"),configured(mine,blank));player.openInventory(inv);}
 public void owned(Player player){Inventory inv=inventory("owned");int slot=menus.getInt("owned.warp-start-slot",10);for(Warp warp:plugin.warps().all())if(warp.owner.equals(player.getUniqueId())&&slot<45)inv.setItem(slot++,warpItem("owned",warp));player.openInventory(inv);}
 public Warp editing(Player player){return editing.get(player.getUniqueId());} public void nextSort(Player player){sort.put(player.getUniqueId(),1-sort.getOrDefault(player.getUniqueId(),0));}
 public String icon(ItemStack item){for(String id:icons.getConfigurationSection("icons").getKeys(false))if(icons.getString("icons."+id+".material").equals(item.getType().name()))return id;return null;}
}
