package nl.bandit.warps.menu;
import nl.bandit.warps.BanditWarpsPlugin; import nl.bandit.warps.model.Warp; import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.inventory.*; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import java.util.*;
public final class TextInputService implements Listener {
 private enum Field { NAME, DESCRIPTION } private record Session(Warp warp,Field field){} private final BanditWarpsPlugin plugin; private final Map<UUID,Session> sessions=new HashMap<>();
 public TextInputService(BanditWarpsPlugin plugin){this.plugin=plugin;}
 public void open(Player player,Warp warp,boolean name){Field field=name?Field.NAME:Field.DESCRIPTION;sessions.put(player.getUniqueId(),new Session(warp,field));String title=plugin.menus().title("text-input."+(name?"name-title":"description-title"));AnvilInventory inv=(AnvilInventory)Bukkit.createInventory(null,InventoryType.ANVIL,title);ItemStack input=new ItemStack(Material.PAPER);ItemMeta meta=input.getItemMeta();meta.setDisplayName(name?warp.name:(warp.description.isBlank()?"Typ hier je beschrijving":warp.description));input.setItemMeta(meta);inv.setItem(0,input);inv.setItem(1,plugin.menus().inputItem("cancel",warp));player.openInventory(inv);}
 @EventHandler public void prepare(PrepareAnvilEvent event){if(!(event.getView().getPlayer() instanceof Player player)||!sessions.containsKey(player.getUniqueId()))return;Session session=sessions.get(player.getUniqueId());String raw=event.getInventory().getRenameText();if(raw==null||raw.isBlank())raw=session.field==Field.NAME?session.warp.name:session.warp.description;ItemStack result=plugin.menus().inputItem("accept",session.warp);ItemMeta meta=result.getItemMeta();meta.setDisplayName("§a§lOpslaan: §f"+raw);result.setItemMeta(meta);event.setResult(result);}
 @EventHandler public void click(InventoryClickEvent event){if(!(event.getWhoClicked() instanceof Player player))return;Session session=sessions.get(player.getUniqueId());if(session==null||event.getView().getTopInventory().getType()!=InventoryType.ANVIL)return;if(event.getRawSlot()==1){event.setCancelled(true);sessions.remove(player.getUniqueId());plugin.menus().settings(player,session.warp);return;}if(event.getRawSlot()!=2)return;event.setCancelled(true);String value=((AnvilInventory)event.getView().getTopInventory()).getRenameText();if(value==null||value.isBlank())return;if(session.field==Field.NAME){if(!value.matches("[A-Za-z0-9_-]{3,20}")){player.sendMessage("§cNaam moet 3-20 tekens zijn, zonder spaties.");return;}if(!value.equalsIgnoreCase(session.warp.name)&&plugin.warps().get(value)!=null){player.sendMessage("§cDie warpnaam bestaat al.");return;}session.warp.name=value;}else{if(value.length()>80){player.sendMessage("§cBeschrijving mag maximaal 80 tekens zijn.");return;}session.warp.description=value;}plugin.warps().put(session.warp);sessions.remove(player.getUniqueId());plugin.menus().settings(player,session.warp);}
 @EventHandler public void close(InventoryCloseEvent event){if(event.getPlayer() instanceof Player player&&event.getInventory().getType()==InventoryType.ANVIL)sessions.remove(player.getUniqueId());}
}
