package nl.bandit.warps.menu;
import nl.bandit.warps.BanditWarpsPlugin; import nl.bandit.warps.model.Warp;
import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.inventory.*; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta;
import java.util.*;

public final class TextInputService implements Listener {
 private enum Field{NAME,DESCRIPTION} private record Input(Warp draft,Field field){}
 private final BanditWarpsPlugin plugin; private final Map<UUID,Input> inputs=new HashMap<>(); private final Set<UUID> returning=new HashSet<>();
 public TextInputService(BanditWarpsPlugin plugin){this.plugin=plugin;}
 public void open(Player player,Warp draft,boolean name){Field field=name?Field.NAME:Field.DESCRIPTION;inputs.put(player.getUniqueId(),new Input(draft,field));AnvilInventory inventory=(AnvilInventory)Bukkit.createInventory(null,InventoryType.ANVIL,plugin.menus().title("text-input."+(name?"name-title":"description-title")));ItemStack paper=new ItemStack(Material.PAPER);ItemMeta meta=paper.getItemMeta();meta.setDisplayName(name?draft.name():(draft.description().isBlank()?"Typ je beschrijving":draft.description()));paper.setItemMeta(meta);inventory.setItem(0,paper);inventory.setItem(1,plugin.menus().inputItem("cancel",draft));player.openInventory(inventory);}
 @EventHandler public void prepare(PrepareAnvilEvent event){if(!(event.getView().getPlayer() instanceof Player player))return;Input input=inputs.get(player.getUniqueId());if(input==null)return;String value=event.getInventory().getRenameText();ItemStack result=plugin.menus().inputItem("accept",input.draft());ItemMeta meta=result.getItemMeta();meta.setDisplayName("§a§lOpslaan §8• §f"+(value==null?"":value));result.setItemMeta(meta);event.setResult(result);}
 @EventHandler public void click(InventoryClickEvent event){if(!(event.getWhoClicked() instanceof Player player))return;Input input=inputs.get(player.getUniqueId());if(input==null||event.getView().getTopInventory().getType()!=InventoryType.ANVIL)return;event.setCancelled(true);if(event.getRawSlot()==1){returnToSettings(player);return;}if(event.getRawSlot()!=2)return;String value=((AnvilInventory)event.getView().getTopInventory()).getRenameText();if(value==null)value="";value=value.trim();if(input.field()==Field.NAME){int min=plugin.getConfig().getInt("validation.name-min-length",3),max=plugin.getConfig().getInt("validation.name-max-length",20);if(value.length()<min||value.length()>max||!value.matches(plugin.getConfig().getString("validation.name-regex","[A-Za-z0-9_-]+"))){plugin.message(player,"invalid-name",Map.of("%min%",String.valueOf(min),"%max%",String.valueOf(max)));return;}if(!plugin.warps().nameAvailable(value,input.draft().id())){plugin.message(player,"name-taken",Map.of("%name%",value));return;}input.draft().name(value);}else{int max=plugin.getConfig().getInt("validation.description-max-length",100);if(value.length()>max){plugin.message(player,"description-too-long",Map.of("%max%",String.valueOf(max)));return;}input.draft().description(value);}returnToSettings(player);}
 private void returnToSettings(Player player){returning.add(player.getUniqueId());inputs.remove(player.getUniqueId());plugin.getServer().getScheduler().runTask(plugin,()->{plugin.menus().openSettings(player);returning.remove(player.getUniqueId());});}
 @EventHandler public void close(InventoryCloseEvent event){if(!(event.getPlayer() instanceof Player player)||event.getInventory().getType()!=InventoryType.ANVIL||returning.contains(player.getUniqueId()))return;if(inputs.remove(player.getUniqueId())!=null)plugin.getServer().getScheduler().runTask(plugin,()->plugin.menus().openSettings(player));}
}
